apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-ibm-cis-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "cert-manager-ibm-cis-webhook.name" . }}
    chart: {{ include "cert-manager-ibm-cis-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "cert-manager-ibm-cis-webhook.name" . }}
    release: {{ .Release.Name }}
