{{- if .Values.clusterIssuer.production.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "dnsimple-webhook.fullname" . }}-production
  labels:
    app: {{ include "dnsimple-webhook.name" . }}
    chart: {{ include "dnsimple-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ include "dnsimple-webhook.fullname" . }}-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            tokenSecretRef:
              key: token
              name: {{ include "dnsimple-webhook.tokenSecretName" . }}
          groupName: {{ .Values.groupName }}
          solverName: dnsimple
{{- end -}}