name: Check PR Labels

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}