name: Contrast SAST Scan

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sast-scan:
    uses: ibm-skills-network/.github/.github/workflows/contrast-sast-scan.yaml@main
    secrets: inherit
